---
title: "Lab 8 Key"
author: "Conner Smith"
date: "11/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(modelsummary)
library(corrplot)
library(broom)
library(here)
```


```{r}
homes <- read_csv(here("data", "slo_homes.csv"))

# Home price is dependent variable 

```


```{r}
# Subset w/ SLO, Atascadero, Arroyo Grande, Santa Maria 

homes_subset <- homes %>% 
  filter(City %in% c("San Luis Obispo", "Atascadero", "Arroyo Grande", "Santa Maria-Orcutt"))

```

```{r, include=FALSE, eval = FALSE}
# Summary table of mean and SD of home prices by city and sale status 
# eval = FALSE --- does not run the code 

homes_subset %>% 
  group_by(City, Status) %>% 
  summarize(mean_price = mean(Price),
            sd_price = sd(Price),
            mean_sqft = mean(SqFt))
```

```{r}
# Explore sqft and home price 

ggplot(data = homes_subset, aes(x = SqFt, y = Price)) +
  geom_point() +
  theme_minimal() +
  geom_smooth(method = "lm")

# when in doubt, don't throw out outliers 
```

```{r}
# Use multiple linear regression to investigate relationships between predictor variables 

# 2 different permutations: (1) Price ~ city, bedrooms, bathrooms, sqft, status (2) Price ~ City, Sqft, Status (3) Try a third one

lm1 <- lm(Price ~ City + Bedrooms + Bathrooms + SqFt + Status, data = homes_subset)

lm2 <- lm(Price ~ City + SqFt + Status, data = homes_subset)

lm3 <- lm(Price ~ SqFt, data = homes_subset)

# Can use summary() for quick comparison 
# To use SLO as references: fct_relevel to specify new reference

# new_homes_subset <- homes_subset %>% 
# mutate(City = fct_relevel(City, "San Luis Obispo")) 

```

```{r}
# Filter for Price:SqFt, find correlation between variables 

homes_quant <- homes_subset %>% 
  select(Price:SqFt)

homes_cor <- cor(homes_quant)

corrplot(homes_cor, method = "ellipse")

```

```{r}
# Compare AIC values 

AIC(lm1)
AIC(lm2)
```

```{r}
# Use mdoel summary to return multiple model outputs 

modelsummary(list(lm1, lm2, lm3))
```

```{r}
# Check diagnostic plots 

plot(lm1)
```

```{r}
# Use broom::augment to return predictions for observations 

home_predictions <- augment(lm1)

# Make a histogram of the residuals 

ggplot(data =  home_predictions, aes(x = .resid))+
  geom_histogram()
```

 # Branches are awesome 
